apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-app-env
  namespace: dev
data:
  PORT: "5500",
  MONGODB_URL: "mongodb://mongodb.default.svc.cluster.local:27017/test",
  REDIS_URL: "redis://redis.default.svc.cluster.local:6379"

