version: '3.7'

services:
  redis:
    image: redis/redis-stack:7.2.0-v6
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - tun_prod
    volumes:
      - ./redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    build: .
    image: backend
    restart: unless-stopped
    command: npm run dev
    ports:
      - 5500:5500
    networks:
      - tun_prod
    depends_on:
      - redis
      - mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongoDB_data:/data
    ports:
      - "27017:27017"
    networks:
      - tun_prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongogui:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      - tun_prod
    environment:
       - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  tun_prod:
    external: true
