x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  redis:
    image: redis/redis-stack:7.2.0-v6
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    networks:
      - tun_prod
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging: *default-logging

  backend:
    build: .
    image: backend
    command: npm run dev
    env_file:
      - .env
    ports:
      - target: 5500
        published: 5500
        protocol: tcp
        mode: host
    networks:
      - tun_prod
    labels:
      - logging=promtail
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    logging: *default-logging
  mongodb:
    image: mongo
    volumes:
      - mongoDB_data:/data/db
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    networks:
      - tun_prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging: *default-logging

  mongogui:
    image: mongo-express
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - tun_prod
    environment:
       - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging: *default-logging

volumes:
  redis_data:
  mongoDB_data:

networks:
  tun_prod:
    external: true
     
