services:
  redis:
    image: redis/redis-stack:7.2.0-v6
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    networks:
      - tun_prod
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    build: .
    image: backend
    command: npm run dev
    env_file:
      - .env
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    networks:
      - tun_prod
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb:
    image: mongo
    volumes:
      - mongoDB_data:/data/db
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    networks:
      - tun_prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongogui:
    image: mongo-express
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - tun_prod
    environment:
       - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  redis_data:
  mongoDB_data:

networks:
  tun_prod:
    external: true
     
