version: '3.7'

services:
  redis:
    image: redis/redis-stack:7.2.0-v6
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - node-network
    volumes:
      - ./redis_data:/data
  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    command: npm run dev
    ports:
      - 5000:5000
    networks:
      - node-network
    depends_on:
      - redis
      - mongodb
  mongodb:
    image: mongo
    container_name: db
    restart: unless-stopped
    volumes:
      - ./mongoDB_data:/data
    ports:
      - "27017:27017"
    networks:
      - node-network
  mongogui:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      - node-network
    environment:
       - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb

networks:
  node-network:
    driver: bridge
    