---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app
  namespace: dev
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: raslensafsaf/backend:v1.1
        ports:
          - containerPort: 5500
        readinessProbe:
          httpGet:
            path: /health
            port: 5500
          periodSeconds: 5
        envFrom:
          - configMapRef:
              name: nodejs-app-env 
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: dev
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
  - name: http
    targetPort: 5500
    port: 80
