name: CI/CD
on: 
  push:
    branches:
      - main
jobs:
  build_push:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_HUB_USERNAME }}/backend:${{ secrets.TAG }}"
      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: "${{ secrets.DOCKER_HUB_USERNAME }}/backend:${{ secrets.TAG }}"
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs app endpoints"
  argocd:
    name: argocd
    needs: build_push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Update deploy.yml for ArgoCD
        run: |
          sed -i "s|image: .*$|image: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${{ secrets.TAG }}|" gitOps/deploy.yml
        shell: bash
      - name: Commit and push deploy.yml update
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git add gitOps/deploy.yml
          git commit -m "Update deploy.yml with new Docker image tag"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}